# Generated by Django 4.1.5 on 2023-01-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_stocks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cus_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.contactform",
                    ),
                ),
                (
                    "stock_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.stocks"
                    ),
                ),
            ],
        ),
    ]
