# Generated by Django 4.1.5 on 2023-01-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_type", models.CharField(max_length=100)),
                ("stock_desc", models.CharField(max_length=200)),
                
            ],
        ),
    ]
