# Generated by Django 4.1.5 on 2023-01-21 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_orders"),
    ]

    operations = [
        migrations.RemoveField(model_name="orders", name="date",),
        migrations.RemoveField(model_name="orders", name="stock_desc",),
        migrations.RemoveField(model_name="orders", name="stock_type",),
        migrations.AddField(
            model_name="orders",
            name="cus_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.contactform",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="stock_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="course.cart"
            ),
            preserve_default=False,
        ),
    ]
