# Generated by Django 4.1.5 on 2023-01-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_remove_orders_date_remove_orders_stock_desc_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart", old_name="stock_id", new_name="cart_id",
        ),
    ]
