# Generated by Django 4.1.5 on 2023-01-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_rename_stock_id_cart_cart_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart", old_name="cart_id", new_name="stock_id",
        ),
    ]
