# Generated by Django 4.1.5 on 2023-01-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_rename_cart_id_cart_stock_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders", old_name="stock_id", new_name="cart_id",
        ),
    ]
