# Generated by Django 4.1.5 on 2023-01-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_rename_stock_id_orders_cart_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders", old_name="cart_id", new_name="stock_id",
        ),
    ]
