# Generated by Django 4.1.5 on 2023-01-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_rename_cart_id_orders_stock_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="stock_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.stocks"
            ),
        ),
    ]
