# Generated by Django 4.1.5 on 2023-01-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0011_alter_orders_stock_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="time",
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
