# Generated by Django 4.1.5 on 2023-01-23 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0012_orders_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 23, 6, 24, 36, 16949, tzinfo=datetime.timezone.utc
                ),
                verbose_name="expiration time (of ad)",
            ),
        ),
    ]
