# Generated by Django 4.1.5 on 2023-01-23 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0013_alter_orders_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 23, 6, 26, 13, 602728, tzinfo=datetime.timezone.utc
                ),
                verbose_name="'expiration time (of ad)'",
            ),
        ),
    ]
