# Generated by Django 4.1.5 on 2023-01-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0015_alter_orders_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="orders", name="time",),
    ]
